/****************************************************************************
**
** DCOP Skeleton generated by dcopidl2cpp from dcoper.cpp
**
** WARNING! All changes made in this file will be lost!
**
*****************************************************************************/

